{
 "title": "Health Tracker",
 "time": { "from": "now-3M", "to": "now" },
 "panels": [
  {
   "title": "Weight",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT WEIGHT, SUBMITTED_ON::DATE, 170 as goal\r\nFROM TRACKER.COMPOSITION;"
    }
   ]
  },
  {
   "title": "Bodyfat",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select bodyfat, submitted_on::date\r\nfrom tracker.composition;"
    }
   ]
  },
  {
   "title": "Average Weight",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT round(avg(weight), 1) as weight, date_trunc('week', submitted_on::date)::date as week\r\nfrom tracker.composition\r\ngroup by 2\r\norder by week asc;"
    }
   ]
  },
  {
   "title": "Average Bodyfat",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT  round(avg(bodyfat), 1) as bodyfat, date_trunc('week', submitted_on::date)::date as week\r\nfrom tracker.composition\r\ngroup by 2\r\norder by week asc;"
    }
   ]
  }
 ]
}